use_frameworks!

platform :ios, '10.0'

target 'TDTagsCollection_Example' do
  pod 'TDTagsCollection', :path => '../'

  target 'TDTagsCollection_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
